* `__address__`
* `__meta_hetzner_cancelled`
* `__meta_hetzner_dc`
* `__meta_hetzner_flatrate`
* `__meta_hetzner_ipv4`
* `__meta_hetzner_name`
* `__meta_hetzner_number`
* `__meta_hetzner_product`
* `__meta_hetzner_project`
* `__meta_hetzner_status`
* `__meta_hetzner_throttled`
* `__meta_hetzner_traffic`
