FROM i386/alpine:3.21@sha256:7b0f18085272db228a5b32fd67f4de1e9690bfae60990971bdb0a324347e2401 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9000
ENTRYPOINT ["/usr/bin/prometheus-hetzner-sd"]
CMD ["server"]
HEALTHCHECK CMD ["/usr/bin/prometheus-hetzner-sd", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/prometheus-hetzner-sd /usr/bin/prometheus-hetzner-sd
