FROM arm32v6/alpine:3.17@sha256:e8748b26b68a624c7d2622ff045ce32b76ea31b50bba8e74989cd9ec84e33bb0 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9000
ENTRYPOINT ["/usr/bin/prometheus-hetzner-sd"]
CMD ["server"]
HEALTHCHECK CMD ["/usr/bin/prometheus-hetzner-sd", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/prometheus-hetzner-sd /usr/bin/prometheus-hetzner-sd
