baseURL = "https://promhippie.github.io/prometheus-hetzner-sd/"
languageCode = "en-us"
title = "Prometheus Hetzner SD"
pygmentsUseClasses = true

disableKinds = ["RSS", "sitemap", "taxonomy", "term", "section"]
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Prometheus service discovery for Hetzner"
  keywords = "prometheus, sd, service, discovery, hetzner, robot"
